FROM oven/bun:1-alpine AS base

WORKDIR /app
COPY package.json ./
COPY bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=base /app/dist ./dist
EXPOSE 4001
CMD ["bun", "run", "dist/main.js"]
